export enum Classes {
  CIM_BIOS_ELEMENT = 'CIM_BIOSElement',
  CIM_BOOT_SERVICE = 'CIM_BootService',
  CIM_BOOT_CONFIG_SETTING = 'CIM_BootConfigSetting',
  CIM_CARD = 'CIM_Card',
  CIM_CHASSIS = 'CIM_Chassis',
  CIM_CHIP = 'CIM_Chip',
  CIM_COMPUTER_SYSTEM_PACKAGE = 'CIM_ComputerSystemPackage',
  CIM_IEEE8021X_SETTINGS = 'CIM_IEEE8021xSettings',
  CIM_KVM_REDIRECTION_SAP = 'CIM_KVMRedirectionSAP',
  CIM_PHYSICAL_MEMORY = 'CIM_PhysicalMemory',
  CIM_PHYSICAL_PACKAGE = 'CIM_PhysicalPackage',
  CIM_POWER_MANAGEMENT_SERVICE = 'CIM_PowerManagementService',
  CIM_PROCESSOR = 'CIM_Processor',
  CIM_SOFTWARE_IDENTITY = 'CIM_SoftwareIdentity',
  CIM_SYSTEM_PACKAGING = 'CIM_SystemPackaging',
  CIM_MEDIA_ACCESS_DEVICE = 'CIM_MediaAccessDevice',
  CIM_WIFI_ENDPOINT_SETTINGS = 'CIM_WiFiEndpointSettings',
  CIM_WIFI_PORT = 'CIM_WiFiPort',
  SERVICE_AVAILABLE_TO_ELEMENT = 'CIM_ServiceAvailableToElement'
}
